# Generated by Django 3.0.2 on 2020-02-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('emp_no', models.CharField(max_length=100)),
                ('emp_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeePostion')),
            ],
        ),
    ]
